### ISSUE TITLE
Experimental rootfs link needs to be updated.

### ISSUE THREAD

**Issue by Danct12** [vanyasem/Halium-Arch#1]
Since your web server is down, is there any other mirror to obtain the experimental rootfs?

**Comment by vanyasem** [comment]
The server was not down, it was being moved from one (physical) location to another. Lookin' better than ever!

**Comment by vanyasem** [comment]
Err, the SSL cert expired, will take a look at that later

**Comment by vanyasem** [comment]
Crazy enough for a Russian dude??
![IMG_2923](https://user-images.githubusercontent.com/13350458/56444512-c4d63300-6301-11e9-8772-1880889bd0fd.jpg)

**Comment by vanyasem** [comment]
I hope it won't cause a fire at my place - that would be sad, I just painted my walls recently

**Comment by Danct12** [comment]
That's some awesome home server setup! Would love to know about the specs.

**Comment by vanyasem** [comment]
@Danct12 here you go
Supermicro MBD-X11SAE-O
Intel Xeon E3-1225 v6
2х8Gb DDR4 2133MHz Kingston (KVR21N15S8K2/16)
AeroCool KCAS-500W

**Comment by hacker1024** [comment]
I can't connect, any chance of an upload to Google Drive or something similar?

**Comment by vanyasem** [comment]
@hacker1024 I apologise, the hosting provider was having some issues. The link is up again
